image main_menu_patreon_idle = "screens/main_menu/images/patreon_idle.webp"
image main_menu_patreon_hover = "screens/main_menu/images/patreon_hover.webp"
image main_menu_discord_idle = "screens/main_menu/images/discord_idle.webp"
image main_menu_discord_hover = "screens/main_menu/images/discord_hover.webp"
image main_menu_ep_idle = "screens/main_menu/images/ep_idle.webp"