image main_menu_patreon_idle = "screens/images/main_menu/patreon_idle.webp"
image main_menu_patreon_hover = "screens/images/main_menu/patreon_hover.webp"
image main_menu_discord_idle = "screens/images/main_menu/discord_idle.webp"
image main_menu_discord_hover = "screens/images/main_menu/discord_hover.webp"
image main_menu_ep4_idle = "screens/main_menu/images/ep4_idle.webp"