image scene_gallery_background = "screens/scene_gallery/images/background.webp"
image scene_gallery_bar_base = "screens/scene_gallery/images/bar_base.webp"
image scene_gallery_bar_thumb = "screens/scene_gallery/images/bar_thumb.webp"
image scene_gallery_button_hover = "screens/scene_gallery/images/button_hover.webp"
image scene_gallery_button_idle = "screens/scene_gallery/images/button_idle.webp"
image scene_gallery_return_hover = "screens/scene_gallery/images/return_hover.webp"
image scene_gallery_return_idle = "screens/scene_gallery/images/return_idle.webp"
image scene_gallery_shadow = "screens/scene_gallery/images/shadow.webp"
