screen patreon_credits(support_link):
    tag end_screen
    modal True
    style_prefix "patreon_credits"

    add "patreon_credits_background"

    viewport id "vp":
        mousewheel True
        draggable True
        ysize 700
        ypos 50

        vbox:
            xfill True

            text "KING" bold True

            null height 25

            text "Chris Jay"
            
            null height 50

            text "PRESIDENT" bold True

            null height 25

            text "Daniel Xu"
            text "Honorin Cohen Salmon"
            text "Venom8797"

            null height 50

            text "SENIOR" bold True

            null height 25

            text "8732487236"
            text "AARon54"
            text "above all else"
            text "Ace"
            text "Agent__PvP"
            text "Aidan Nicholson"
            text "AJ"
            text "Alejandro Perez"
            text "Alejandro Salazar-Padilla"
            text "Alex"
            text "alex holt"
            text "alex keller"
            text "Alexander Felber"
            text "Alien Hand"
            text "Allbran_1996"
            text "ammopackrat"
            text "Andrew"
            text "andrew brick"
            text "Andrew Robley"
            text "Andrew Stevenson"
            text "Anthony Young"
            text "Asd"
            text "AuRa Cyclopes"
            text "AUSTIN M SMITH"
            text "Ayax"
            text "B"
            text "B Ward Jr"
            text "Benjamin Quaade"
            text "BestNameEver"
            text "Bielska"
            text "Big Mike"
            text "BigHead"
            text "Billy Bob"
            text "bjarne lykke"
            text "Blackout_8"
            text "Blackshark00"
            text "Blake S"
            text "Boa"
            text "Bob Smith"
            text "Bot_Kenobi"
            text "Brad Brantley"
            text "Brandon McDonald"
            text "Bray"
            text "BrendenM"
            text "Brian Vu"
            text "Briek Scheldeman"
            text "Brocke Potts"
            text "Brownaaa"
            text "Bryan D Sanchez"
            text "Btank"
            text "Buh-Buh-Bacon"
            text "Bus"
            text "Caio Keunecke"
            text "CAS89"
            text "Catastrophr"
            text "Chanel Coco"
            text "Chester"
            text "Chris Miller"
            text "Christian"
            text "Christian Jusino"
            text "CM21334784"
            text "coastalcosby"
            text "Collin"
            text "Collin Thompson"
            text "Connor"
            text "ConstableBleep"
            text "Crash 1269"
            text "DaddyDyrroth"
            text "Damien Norris"
            text "Dan Plug"
            text "dan tripiccione"
            text "Danial Maul"
            text "Daniel G"
            text "Daniel Gisin"
            text "Daniel Walz"
            text "Dante Vega"
            text "DarkLance880"
            text "David Egelund"
            text "David Smigiel"
            text "David Stewart"
            text "Declan Tracey"
            text "Devin Hall"
            text "Dinesh Arunkumar"
            text "dirk stoltenberg"
            text "DIVINER SUNSET"
            text "Dom Romeo"
            text "Douglas Dreier"
            text "DR Wazzabee"
            text "DriftDevil"
            text "Drurkux"
            text "Dylan  Souksengdao"
            text "Dylan Bose"
            text "Edward James"
            text "Elias Drake"
            text "Emanuel Muresan"
            text "Erik Rubino"
            text "Erol Altan"
            text "EstuaryGuy"
            text "Evan Bremner"
            text "extra"
            text "Falko Meyer"
            text "fivenights"
            text "Franky Olmos"
            text "Freddo Findlay"
            text "Full blood prince"
            text "G Green"
            text "Gav Yng"
            text "glb1998"
            text "Goobie"
            text "Greg Brown"
            text "GregT"
            text "Groovy"
            text "grysk"
            text "Gwen Stacy"
            text "Hai Nguyen"
            text "HaydenFromTarget"
            text "Heath Miller"
            text "Hederick"
            text "Henrik"
            text "Hyades52"
            text "Iconas"
            text "Ioannis Gomez"
            text "IVDX BLCK"
            text "j"
            text "J Lynch"
            text "jack wish"
            text "James"
            text "James Vavala"
            text "Jarood"
            text "Jase"
            text "Jason Cordray"
            text "Jason Vargas"
            text "Jason Xu"
            text "Javibrazy"
            text "Jay"
            text "Jay Furusho"
            text "Jay Wolfe"
            text "JB93"
            text "Jeff Torres"
            text "Jeremy B"
            text "jim pet"
            text "Jimmy Gumz"
            text "jodnecroman"
            text "joe"
            text "john"
            text "John Carlson"
            text "John MacLeod"
            text "Johnny"
            text "Jonathan Kessler"
            text "Jonathon Gonzalez"
            text "Jordan Cash"
            text "Jorge1620"
            text "jose"
            text "Joseph stauder"
            text "Josh"
            text "Josh Calles"
            text "Josh Didier"
            text "Josh Shaffer"
            text "Joshua Hughes"
            text "Justin"
            text "Kaden"
            text "Kahbe"
            text "Kai Guy Incognito"
            text "Keiran Dawson"
            text "Keith Mcchristy"
            text "Kenny"
            text "Kevin Bernabe"
            text "King Hugi"
            text "Kraz Z"
            text "Krouchka"
            text "KvngChaos"
            text "Kyle"
            text "Kyle Pollock"
            text "Kyle Wandelear"
            text "Larry"
            text "Lasivren"
            text "Laterius Neely"
            text "LazyPigeon"
            text "Lee Turner"
            text "Leo"
            text "Leroy Lane"
            text "LIldj227"
            text "LoganD1975"
            text "Louis"
            text "LukasA"
            text "Lumberjack"
            text "lxtommy"
            text "M3ch87"
            text "Malviris"
            text "Marcus"
            text "Marcus Hite"
            text "Marisa Hall"
            text "Mark Hughes"
            text "Martin Barth"
            text "Matt"
            text "Matt Cable"
            text "Matt L"
            text "Max Reusser"
            text "Mel Maldonado"
            text "Messy"
            text "Michael Schneider"
            text "Miguel Gonçalves"
            text "Miguel-Martin Claeys"
            text "Mike"
            text "Mikel George"
            text "Mitchell Hagen"
            text "Nagit0"
            text "Naoero"
            text "Narayan Shankar"
            text "Nat"
            text "Nate Diaz"
            text "Neri"
            text "Niccolado"
            text "Niccolo Naccarelli"
            text "Nonefots"
            text "Nonyanan"
            text "Nooope"
            text "NovaPrime7"
            text "Oma"
            text "onfaiofnioe"
            text "OppaiMan"
            text "owskii444"
            text "PacFu"
            text "Panoramic Fx"
            text "Paul Stepro"
            text "pellepaltnacke"
            text "Penatrator"
            text "Pentaur"
            text "Peter Bauer"
            text "Petr"
            text "Philip"
            text "Pionier 101"
            text "PlaguedCastiel"
            text "Podo_Games"
            text "Rafael Batalla"
            text "Raumgar"
            text "Raymond Taulbee"
            text "Ree"
            text "Rene Lara"
            text "ricardo"
            text "Richie Tran"
            text "Ricky Smith"
            text "Robert Camilleri"
            text "Robert Grimes"
            text "Robert J Maggio"
            text "Rogan5"
            text "rollorob"
            text "Ronny Moran"
            text "Ronny Padilla"
            text "Ryan Briggs"
            text "Ryan King"
            text "S"
            text "SaintsM455Acre"
            text "Sam"
            text "Scott Fujiwara"
            text "scottie schmutz"
            text "Sean Cook"
            text "Sebastien NICAS"
            text "Sempit"
            text "Sfthkghj"
            text "Shinji Ikari"
            text "Siftdagger"
            text "SilentHornet"
            text "Skyler"
            text "skylynx007"
            text "Sonicsauke36"
            text "Spartan Clan"
            text "Spencer Ly"
            text "Stephen Fish"
            text "Steven"
            text "Strohmy86"
            text "Tad Stemen"
            text "Tanishk Zac"
            text "Tanner McCleave"
            text "The Tree"
            text "TheGeneric"
            text "Thomas Buchta"
            text "Thomas E Davis Jr"
            text "Thomas G."
            text "Thomas Hotchkiss"
            text "TigerTheSaiyan"
            text "tj boroff"
            text "Tobias"
            text "Tom Gay"
            text "Tony Horne"
            text "Trent Schacht"
            text "Trevor"
            text "Tsqrrl"
            text "Tyler"
            text "Tyler Kulbacki"
            text "Tytamice"
            text "UnholyCandle"
            text "Urrius"
            text "Valor Nebula"
            text "VanHungWell"
            text "Varisheer"
            text "Vendetta-ViBES"
            text "Victor Luu"
            text "W1nz"
            text "Wallaby Way"
            text "Walter White"
            text "Wang Calvin"
            text "Weiss"
            text "WILDTAT"
            text "wilson cao"
            text "Wise"
            text "Wladislaw Müller"
            text "Yann Gilles"
            text "yopokematt"
            text "Zach"
            text "zenlunatic"
            text "Zephyr"
            text "Zhou W."
            text "석민 윤"

            null height 50

            text "Special Thanks" bold True

            null height 25

            text "KingLui"
            text "OscarSix"
            text "Pete"
            text "Ben Davis"
            text "Nicki5617"
            text "NicoMS"
            text "Mugi"
            text "TheFatLebowski"
            text "Francois"
            text "RogueRoach"
            text "Zoneh69"
            text "Filip Jankovic"
            text "Mozzart"
            text "Spacestorm"
            text "Smudger"
            text "StefanGaming"

    add "scene_gallery_bar_base" pos (1200, 50) xysize (27, 700)
    vbar:
        pos (1205, 55)
        xysize (17, 690)
        base_bar "#0000"
        thumb "gui/bar/bar_thumb.webp"
        value YScrollValue("vp")

    imagebutton:
        idle "support_development_idle"
        hover "support_development_hover"
        action OpenURL(support_link)
        xalign 0.5
        ypos 735

    hbox:
        align (0.5, 1.0)

        imagebutton:
            idle "main_menu_idle"
            hover "main_menu_hover"
            action MainMenu()
            yalign 0.5

        imagebutton:
            idle "team_idle"
            hover "team_hover"
            action Show("team_credits", None, support_link)
            yalign 0.5

    on "show" action [SetVariable("quick_menu", False), Play("music", "audio/music/common/vocal.mp3")]
    on "hide" action SetVariable("quick_menu", True)
    on "replace" action SetVariable("quick_menu", False)
    on "replaced" action SetVariable("quick_menu", True)


style patreon_credits_text is text:
    font "fonts/Montserrat-Regular.ttf"
    size 36
    xalign 0.5